scenario:
  name: cryptoadmin
  provider:
    name: telegram
    token: '2140952227:AAEdQDEL2kuQByeUaYRIga4sutd3TcF4fko'

  states:
    -
      name: unknown
      transitions:
        - {name: to_start, state_to: start, command: {type: 'text_input', arguments: ['/start']}}

    -
      name: start
      actions:
        send_text:
          name: send_text
          params:
            text: >
              Панель управления ботом PULS PAY
      transitions:
        - {name: to_start, state_to: start, command: {type: 'text_input', arguments: ['/start']}}
        - {name: to_confirm, state_to: confirm_1, command: {type: 'recognize_order', arguments: [true]}}
        - {name: to_confirm_2, state_to: confirm_1, command: {type: 'recognize_order', arguments: [false]}}

    -
      name: confirm_1
      actions:
        send_text:
          name: send_text
          params:
            text: >
              Сделка завершена успешно
      transitions:
        - {name: to_start, state_to: start, command: {type: 'text_input', arguments: ['/start']}}
        - { name: to_confirm, state_to: confirm_1, command: { type: 'recognize_order', arguments: [ true ] } }
        - { name: to_confirm_2, state_to: confirm_1, command: { type: 'recognize_order', arguments: [ false ] } }

    -
      name: confirm_2
      actions:
        send_text:
          name: send_text
          params:
            text: >
              Сделка отменена
      transitions:
        - {name: to_start, state_to: start, command: {type: 'text_input', arguments: ['/start']}}
        - { name: to_confirm, state_to: confirm_1, command: { type: 'recognize_order', arguments: [ true ] } }
        - { name: to_confirm_2, state_to: confirm_1, command: { type: 'recognize_order', arguments: [ false ] } }
#
#    -
#      name: confirm_2
#      actions:
#        confirm_order:
#          name: confirm_order
#        send_text:
#          name: send_text
#          params:
#            text: >
#              Сделка подтверждена.
#      transitions:
#        - {name: to_start, state_to: start, command: {type: 'instant'}}
