scenario:
  name: cryptoadmin
  provider:
    name: telegram
    token: '2140952227:AAEdQDEL2kuQByeUaYRIga4sutd3TcF4fko'

  states:
    -
      name: unknown
      transitions:
        - {name: to_start, state_to: start, command: {type: 'text_input', arguments: ['/start']}}

    -
      name: start
      actions:
        send_text:
          name: send_text
          params:
            text: >
              Панель управления
      transitions:
        - {name: to_confirm, state_to: confirm_1, command: {type: 'button', arguments: ['/confirm', 'Подтвердить заказ']}}

    -
      name: confirm_1
      actions:
        send_text:
          name: send_text
          params:
            text: >
              Отправьте код завершения сделки.
      transitions:
        - {name: to_confirm_2, state_to: confirm_2, command: {type: 'text_input'}}

    -
      name: confirm_2
      actions:
        confirm_order:
          name: confirm_order
        send_text:
          name: send_text
          params:
            text: >
              Сделка подтверждена.
      transitions:
        - {name: to_start, state_to: start, command: {type: 'instant'}}
