scenario:
  name: cryptoadmin
  provider:
    name: telegram
    token: '2140952227:AAEdQDEL2kuQByeUaYRIga4sutd3TcF4fko' # '5386545649:AAH6tlS_9JkXYimiAtA1gzHMI8RA9jiu-1M' #

  states:
    - name: unknown
      transitions:
        - { name: to_start, state_to: start, command: { type: 'text_input', arguments: [ '/start' ] } }

    - name: start
      actions:
        send_text:
          name: send_text
          params:
            text: >
              Панель управления ботом PULS PAY
      transitions:
        - { name: to_start, state_to: start, command: { type: 'text_input', arguments: [ '/start' ] } }
        - { name: to_confirm, state_to: confirm_1, command: { type: 'preorder_processing', arguments: [ true ] } }
        - { name: to_confirm_8, state_to: confirm_8, command: { type: 'preorder_processing', arguments: [ false ] } }
        - { name: to_start_2, state_to: start, command: { type: 'payment_processing', arguments: [ true ] } }
        - { name: to_start_2, state_to: start, command: { type: 'payment_processing', arguments: [ false ] } }

    - name: confirm_1
      actions:
        remember_name:
          name: remember_input
          params: { var: 'current_order_marker' }
        send_text:
          name: send_text
          params:
            text: >
              Введите номер карты на которую пользователь должен отправить средства
      transitions:
        - { name: to_confirm_1_2, state_to: confirm_1_2, command: { type: 'text_input' } }
        - { name: to_confirm_1, state_to: confirm_1, command: { type: 'preorder_processing', arguments: [ true ] } }
        - { name: to_confirm_8, state_to: confirm_8, command: { type: 'preorder_processing', arguments: [ false ] } }
        - { name: to_start_2, state_to: start, command: { type: 'payment_processing', arguments: [ true ] } }
        - { name: to_start_2, state_to: start, command: { type: 'payment_processing', arguments: [ false ] } }

    - name: confirm_1_2
      actions:
        remember_name:
          name: remember_input
          params: { var: 'current_order_payment_address' }
      transitions:
        - { name: to_confirm_1_3, state_to: confirm_1_3, command: { type: 'instant' } }

    - name: confirm_1_3
      actions:
        send_payment_address:
          name: send_payment_address
      transitions:
        - { name: to_confirm_1_4, state_to: confirm_1_4, command: { type: 'instant' } }

    - name: confirm_1_4
      actions:
        st:
          name: send_text
          params:
            text: Номер карты отправлен пользователю.
      transitions:
        - { name: to_start, state_to: start, command: { type: 'text_input', arguments: [ '/start' ] } }
        - { name: to_confirm, state_to: confirm_1, command: { type: 'preorder_processing', arguments: [ true ] } }
        - { name: to_confirm_8, state_to: confirm_8, command: { type: 'preorder_processing', arguments: [ false ] } }
        - { name: to_start_2, state_to: start, command: { type: 'payment_processing', arguments: [ true ] } }
        - { name: to_start_2, state_to: start, command: { type: 'payment_processing', arguments: [ false ] } }

    - name: confirm_8
      actions:
        send_text:
          name: send_text
          params:
            text: >
              Сделка отменена
      transitions:
        - { name: to_start, state_to: start, command: { type: 'text_input', arguments: [ '/start' ] } }
        - { name: to_confirm, state_to: confirm_1, command: { type: 'preorder_processing', arguments: [ true ] } }
        - { name: to_confirm_8, state_to: confirm_8, command: { type: 'preorder_processing', arguments: [ false ] } }
        - { name: to_start_2, state_to: start, command: { type: 'payment_processing', arguments: [ true ] } }
        - { name: to_start_2, state_to: start, command: { type: 'payment_processing', arguments: [ false ] } }

