version: "3.3"

services:
  web:
    build: go
    image: crypto/web
    container_name: web
    restart: always
    ports:
      - "80:8181"
    volumes:
      - ../:/app
    networks:
      - crypto

  db:
    build: postgres
    image: crypto/db
    container_name: db
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - "./volumes/pgdata:/var/lib/postgresql/data"
      - "./volumes/data:/opt/data"
    tmpfs:
      - /run
      - /tmp
    ports:
      - "127.0.0.1:5432:5432"
    networks:
      - crypto

networks:
  crypto:
    external: true