entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
#
#tls:
#  certificates:
#    - certFile: "/certs/moofik.com.crt"
#      keyfile: "/certs/moofik.com.key"

certificatesResolvers:
  letsencrypt:
    acme:
      email: moofik12@gmail.com
      storage: /app/acme.json
      httpChallenge:
        entryPoint: web
